
DROP TABLE WebUser CASCADE;
DROP TABLE Sport CASCADE;
DROP TABLE Position CASCADE;
DROP TABLE Plays CASCADE;
DROP TABLE Rating CASCADE;
DROP TABLE Friend CASCADE;
DROP TABLE Game CASCADE;
DROP TABLE Joined CASCADE;
DROP TABLE Comment CASCADE;

DROP FUNCTION search CASCADE;

DROP TYPE searchCriteria CASCADE;
DROP TYPE searchResult CASCADE;
